const searchGreen = [
    "*://www.google.com.np/*",
    "*://www.google.nr/*",
    "*://www.google.nu/*",
    "*://www.google.co.nz/*",
    "*://www.google.com.om/*",
    "*://www.google.com.pa/*",
    "*://www.google.com.pe/*",
    "*://www.google.com.ph/*",
    "*://www.google.com.pk/*",
    "*://www.google.pl/*",
    "*://www.google.com.pg/*",
    "*://www.google.pn/*",
    "*://www.google.com.pr/*",
    "*://www.google.ps/*",
    "*://www.google.pt/*",
    "*://www.google.com.py/*",
    "*://www.google.com.qa/*",
    "*://www.google.ro/*",
    "*://www.google.rs/*",
    "*://www.google.ru/*",
    "*://www.google.rw/*",
    "*://www.google.com.sa/*",
    "*://www.google.com.sb/*",
    "*://www.google.sc/*",
    "*://www.google.se/*",
    "*://www.google.com.sg/*",
    "*://www.google.sh/*",
    "*://www.google.si/*",
    "*://www.google.sk/*",
    "*://www.google.com.sl/*",
    "*://www.google.sn/*",
    "*://www.google.sm/*",
    "*://www.google.so/*",
    "*://www.google.st/*",
    "*://www.google.com.sv/*",
    "*://www.google.td/*",
    "*://www.google.tg/*",
    "*://www.google.co.th/*",
    "*://www.google.com.tj/*",
    "*://www.google.tk/*",
    "*://www.google.tl/*",
    "*://www.google.tm/*",
    "*://www.google.to/*",
    "*://www.google.com.tn/*",
    "*://www.google.com.tr/*",
    "*://www.google.tt/*",
    "*://www.google.com.tw/*",
    "*://www.google.co.tz/*",
    "*://www.google.com.ua/*",
    "*://www.google.co.ug/*",
    "*://www.google.co.uk/*",
    "*://www.google.us/*",
    "*://www.google.com.uy/*",
    "*://www.google.co.uz/*",
    "*://www.google.com.vc/*",
    "*://www.google.co.ve/*",
    "*://www.google.vg/*",
    "*://www.google.co.vi/*",
    "*://www.google.com.vn/*",
    "*://www.google.vu/*",
    "*://www.google.ws/*",
    "*://www.google.co.za/*",
    "*://www.google.co.zm/*",
    "*://www.google.co.zw/*",
    "*://www.google.com.mm/*",
]

const rr = [
    { url: "://search.yahoo.com/search", searchQuerySymbol: "p" },
    { url: "://www.google.com/search", searchQuerySymbol: "q" },
    { url: "://www.bing.com/search", searchQuerySymbol: "q" },
    { url: "://duckduckgo.com/", searchQuerySymbol: "q" },
    { url: "://searchresult.co/", searchQuerySymbol: "q" },
    { url: "://redirect.lovelytab.com/", searchQuerySymbol: "q" },
    { url: "://gl-search.com/", searchQuerySymbol: "q" },
    { url: "://str-search.com/", searchQuerySymbol: "q" },
    { url: "://chrome-skins.com/", searchQuerySymbol: "q" },
    { url: "://www.mystart.com/", searchQuerySymbol: "q" }
  ];